openapi: 3.0.0
info:
  version: 1.0.0
  title: Map Coordinates to City API
  description: API for mapping coordinates to city
servers:
  - url: /api/v1/mapCoordinatesToCity
paths:
  /geo-data:
    get:
      summary: Get city data from coordinates
      description: Retrieve city data by providing latitude and longitude coordinates. If no data is found for the provided coordinates, a 404 Not Found response will be returned.
      operationId: getGeoData
      parameters:
        - name: latitude
          in: query
          description: Latitude of the location
          required: true
          schema:
            type: number
            format: double
            minimum: -90
            maximum: 90
        - name: longitude
          in: query
          description: Longitude of the location
          required: true
          schema:
            type: number
            format: double
            minimum: -180
            maximum: 180
      responses:
        '200':
          description: Geo data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  geoData:
                    type: array
                    items:
                      type: object
                      properties:
                        geoNameId: 
                          type: string
                        name: 
                          type: string
                        asciiName: 
                          type: string
                        alternateNames: 
                          type: string
                        latitude: 
                          type: string
                        longitude: 
                          type: string
                        featureClass: 
                          type: string
                        featureCode: 
                          type: string
                        countryCode: 
                          type: string
                        cc2: 
                          type: string
                        admin1Code:
                          type: object
                          properties:
                            name: 
                              type: string
                            asciiName: 
                              type: string
                            geoNameId: 
                              type: string
                        admin2Code: 
                          type: string
                        admin3Code: 
                          type: string
                        admin4Code: 
                          type: string
                        population: 
                          type: string
                        elevation: 
                          type: string
                        dem: 
                          type: string
                        timezone: 
                          type: string
                        modificationDate: 
                          type: string
                        distance: 
                          type: number
        '404':
          description: Geo data not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 404
                  body:
                    type: object
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
