name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  testAndBuild:
    name: Check the source code
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      PORT: ${{ secrets.PORT }}
      IS_RATING_SCRAPING_BACKGROUND_WORKER_ENABLED: ${{ secrets.IS_RATING_SCRAPING_BACKGROUND_WORKER_ENABLED }}
      RATING_BACKGROUND_WORKER_SCRAPING_INTERVAL: ${{ secrets.RATING_BACKGROUND_WORKER_SCRAPING_INTERVAL }}
      MAX_RATING_SCRAPING_QUEUE_SIZE: ${{ secrets.MAX_RATING_SCRAPING_QUEUE_SIZE }}
      ERROR_LOG_LEVEL: ${{ secrets.ERROR_LOG_LEVEL }}
      REQ_RES_LOG_LEVEL: ${{ secrets.REQ_RES_LOG_LEVEL }}
      SERVER_INSTANCE_ID: ${{ secrets.SERVER_INSTANCE_ID }}
      MONGO_RATING_DB_URL: ${{ secrets.MONGO_RATING_DB_URL }}
      AGODA_API_KEY: ${{ secrets.AGODA_API_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Run prettier check
        run: yarn run prettierCheck

      - name: Lint
        run: yarn run lintQuiet

      - name: Run tests
        run: yarn run test

      - name: Build project
        run: yarn run build
